apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.serviceName }}-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: {{ .Values.serviceName }}-secret
    creationPolicy: Owner
  data:
  {{- range .Values.secureSecrets }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.serviceName }}/secret
        property: {{ . }}
  {{- end }}
