spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${DB_NAME:ui_db}?allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:admin}
    password: ${MYSQL_PASSWORD:}
    hikari:
      maximum-pool-size: 10   # 너무 높지 않게 제한
      idle-timeout: 600000    # 10분
      max-lifetime: 1800000   # 30분
      connection-timeout: 30000
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: none  # 운영환경에서는 update 대신 none
    show-sql: false   # 운영환경에서는 SQL 로그 비활성화
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb+srv://user:goorm0508@goorm-mongodb.svz66jf.mongodb.net/?retryWrites=true&w=majority&appName=goorm-mongoDB}
      database: content-db
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration