apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-service-config
  namespace: ui
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_SERVER_PORT: "8086"
  EUREKA_URL: http://eureka-service.default.svc.cluster.local:8761/eureka
