apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service
  namespace: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-service
  template:
    metadata:
      labels:
        app: ui-service
    spec:
      containers:
        - name: ui-service
          image: roin09/ui-service:latest
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: ui-service-config
            - secretRef:
                name: ui-service-secret
