nameOverride: ui
fullnameOverride: ui-service
image:
  repository: roin09/ui-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

env:
  useConfigMap: true
  useSecret: true

replicaCount: 1

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: false
  host: ""

externalSecret:
  enabled: true
  refreshInterval: 1h
  secretStore:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  dataFromKey: ui-service-secret

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-type
              operator: In
              values:
                - high

resources:
  requests:
    cpu: 300m
    memory: 384Mi
  limits:
    cpu: 500m
    memory: 512Mi
