nameOverride: ui
fullnameOverride: ui-service
image:
  repository: roin09/ui-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8086
  targetPort: 8086

env:
  useConfigMap: true
  useSecret: true

replicaCount: 1

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: false
  host: "api.aws-test-site.shop"

externalSecret:
  enabled: true
  refreshInterval: 1h
  secretStore:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  dataFromKey: ui-service-secret

affinity: {}

resources:
  requests:
    cpu: 300m
    memory: 384Mi
  limits:
    cpu: 500m
    memory: 512Mi
