replicaCount: 1

image:
  repository: roin09/ui-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

config:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_SERVER_PORT: "8086"
  S3_FRONTEND_ORIGIN: http://goorm-front.s3-website.ap-northeast-2.amazonaws.com
  KAFKA_BOOTSTRAP_SERVERS: 43.201.43.88:9092, 15.165.234.219:9092, 15.165.234.219:9092
  KAFKA_SCHEMA_REGISTRY_SERVER: 3.38.204.173:8081

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75

topologySpreadConstraints:
  enabled: true
  maxSkew: 1
  topologyKey: topology.kubernetes.io/zone

podAntiAffinity:
  enabled: true

useSecret: false
