apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui-service
spec:
  project: default
  source:
    repoURL: https://github.com/GoormPlay/ui-service.git
    targetRevision: deploy
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: ui
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
